/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

/**
 * A custom resource that is used by the function.
 */
export interface CustomResource {
    /**
     * A custom resource that is used by the function.
     */
    custom: {
        /**
         * The ARN of the custom resource.
         */
        arn: string | string[]
        /**
         * Custom IAM actions to add to the role.
         */
        iamActions: string[]
    }
}
