/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

type DynamodbResourceActionsArray = 'read' | 'write' | 'scan' | 'delete' | 'put' | 'update' | 'get' | 'query'

/**
 * A DynamoDB table that is used by the function.
 */
export interface DynamodbResource {
    /**
     * A DynamoDB table that is used by the function.
     */
    dynamodb: {
        /**
         * The ID of the table.
         */
        tableId: string
        actions: [DynamodbResourceActionsArray, ...DynamodbResourceActionsArray[]]
    }
}
