/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

/**
 * An SSM parameter that is used by the function.
 */
export interface ParameterResource {
    parameter:
        | string
        | {
              /**
               * The path to the SSM parameter.
               */
              path: string
              actions: ['read', ...'read'[]]
          }
}
