/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { ApigatewayMonitoringMetric } from '../../monitoring/apigateway.type.js'

export interface HttpTrigger {
    /**
     * Subscribes to an HTTP route.
     */
    http: {
        method: 'get' | 'post' | 'put' | 'delete' | 'patch' | 'options' | 'head'
        /**
         * The HTTP path for the route. Must start with / and must not end with /.
         */
        path: string
        /**
         * The authorizer to use for the route, this overrides the default authorizer.
         */
        authorizer?:
            | {
                  /**
                   * The name of the authorizer to use for the route.
                   */
                  name: string
                  /**
                   * The scopes to use for the authorizer.
                   */
                  scopes?: string[] | undefined
              }
            | undefined
        /**
         * The monitoring configuration for the route.
         */
        monitoring?: ApigatewayMonitoringMetric | undefined
    }
}
