/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import type { FooData } from '../../lib/response.type.js'

import type { DefinedError, ValidateFunction } from 'ajv'

import { validate as FooResponseValidator } from './schemas/foo-response.schema.js'

export interface FooResponse {
    data: FooData
}

export const FooResponse = {
    validate: FooResponseValidator as ValidateFunction<FooResponse>,
    get schema() {
        return FooResponse.validate.schema
    },
    get errors() {
        return FooResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is FooResponse => FooResponse.validate(o) === true,
    parse: (o: unknown): { right: FooResponse } | { left: DefinedError[] } => {
        if (FooResponse.is(o)) {
            return { right: o }
        }
        return { left: (FooResponse.errors ?? []) as DefinedError[] }
    },
} as const
