/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface PublishEventbridge {
    /**
     * Publishes an event to an EventBridge event bus.
     */
    eventbridge: {
        /**
         * The name of the event bus to publish to.
         */
        eventBusId: string
        /**
         * The detail type of the event.
         */
        detailType: string | string[]
    }
}
