/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import type { PublishEventbridge } from './eventbridge.type.js'
import type { PublishSqs } from './sqs.type.js'

/**
 * The events that the handler may publish.
 */
export type Publishes = (PublishEventbridge | PublishSqs)[]
