/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

/**
 * Publishes an event to an SQS queue.
 */
export interface PublishSqs {
    sqs: {
        /**
         * The ID of the SQS queue to publish to.
         */
        queueId: string
    }
}
