/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface AnomalyMetric {
    enabled?: boolean | undefined
    evaluationPeriods?: number | undefined
    datapointsToAlarm?: number | undefined
    bandWidthStandardDeviations?: number | undefined
    metricPeriod?: number | undefined
}

export interface StaticMetric {
    enabled?: boolean | undefined
    threshold?: number | undefined
    period?: number | undefined
    evaluationPeriods?: number | undefined
}
