/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

import type { ApigatewayMonitoring, LambdaMonitoring, SqsMonitoring } from './metrics.type.js'

export interface Monitoring {
    httpApi?: ApigatewayMonitoring | undefined
    restApi?: ApigatewayMonitoring | undefined
    sqs?: SqsMonitoring | undefined
    lambda?: LambdaMonitoring | undefined
}
