/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface ScheduledTrigger {
    /**
     * Subscribes to a scheduled event.
     */
    schedule: {
        /**
         * The name to give the scheduled rule. Defaults to prefixing the name of the handler.
         */
        ruleName?: string | undefined
        /**
         * The prefix to give the scheduled rule. Defaults to the name of the handler.
         */
        ruleNamePrefix?: string | undefined
        /**
         * The description to give the scheduled rule.
         */
        description?: string | undefined
        /**
         * The rate at which to invoke the handler. Must be a valid rate expression. See https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html for more information.
         */
        rate: string
        /**
         * Whether the rule should be enabled. Defaults to true.
         */
        enabled?: boolean | undefined
        /**
         * The input to pass to the handler. Defaults to an empty object. Conflicts with inputPath and inputTransformer
         */
        input?: unknown
        /**
         * The JSONPath to use to extract the input to pass to the handler. Conflicts with input and inputTransformer.
         */
        inputPath?: string | undefined
        /**
         * The input transformer to use to transform the input to pass to the handler. Conflicts with input and inputPath. See https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-transform-target-input.html for more information.
         */
        inputTransformer?:
            | {
                  /**
                   * The JSONPaths to use to extract the input to pass to the handler.
                   */
                  inputPaths?:
                      | {
                            [k: string]: string | undefined
                        }
                      | undefined
                  /**
                   * The template to use to transform the input to pass to the handler.
                   */
                  inputTemplate: string
              }
            | undefined
    }
}
